cursor #e6f0ff
cursor_text_color #ffffff

foreground            #e6f0ff
background            #000000
selection_foreground  #000000
selection_background  #999999
url_color             #ffffff

color0   #000000
color1   #f26060
color2   #5ebf42
color3   #ffd93f
color4   #ffffff
color5   #ffffff
color6   #FFFFFF
color7   #474444
color8   #040000
color9   #ff7f7f
color10  #91ff72
color11  #ffdc4c
color12  #ffffff
color13  #ffffff
color14  #ffffff
color15  #fff9f9
